### ISSUE TITLE
All types getting tagged with 'Function'

### ISSUE THREAD

**Issue by anbuanand** [jon49/json-schema-to-mongoose#2]
Input:- 
Valid JSON..

  'addressLine1': {
          'type': 'string'
        },
        'addressLine2': {
          'type': 'string'
        },
-------------------OUTPUT -----------------------
address:
   { addressLine1: { type: [Function: String] },
     addressLine2: { type: [Function: String] },
     city: { type: [Function: String] },
     postalCode: { type: [Function: String] } },
===================

Why is this extra string "Function" coming ??

**Comment by jon49** [comment]
The `Function` is just telling you that that value at that point is a `Function` called `String`. This is expected. If you have `output` being the OUTPUT you would see `output.addressLine1.type(1)` be `"1"`.

**Comment by anbuanand** [comment]
Hi Jon,
But Mongoose schema ( the output) does not support "Function" keyword.. so
what is the solution?
i.e instead of ' { type: [Function: String] },'  , it has to be only ' {
type: String }'

I am using the generated Mongoose schema for the further get from db.. so
it fails if they word 'Function' is there..
had to manually remove it from the generated schema.
So please let me know ..

On Tue, Sep 22, 2015 at 10:01 PM, Jon Nyman <notifications@github.com>
wrote:

> The Function is just telling you that that value at that point is a
> Function called String. This is expected. If you have output being the
> OUTPUT you would see output.addressLine1.type(1) be "1".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jon49/json-schema-to-mongoose/issues/2#issuecomment-142341680>
> .
>



-- 
Thanks,
Anbu

**Comment by jon49** [comment]
Can you show me the code that that you are using that puts `Function` in the actual code?
