### ISSUE TITLE
Input parameters and supported json schema keywords not described in a README

### ISSUE THREAD

**Issue by mickyloranger** [jon49/json-schema-to-mongoose#3]
In your README file you provide the following example:
```javascript
var mongooseSchema = createMongooseSchema(refs, schema)
```
Could you please provide more details about the parameters `refs` and `schema`? And also supported json schema  keywords.

I have schema looking like this:

```javascript
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://mydomain.net/schemas/enduser.json",
  "type": "object",
  "properties": {
    "personaldata": {
      "$ref": "http://mydomain.net/schemas/personaldata.json"
    }
  },
  "additionalProperties": false,
  "required": [
    "personaldata"
  ]
}
```
but i can't generate a mongoose schema with your module. Is there any possibility for that?

**Comment by jon49** [comment]
See https://github.com/jon49/json-schema-to-mongoose#usage for usage and examples of `refs` and `schema`.

It doesn't support remote refs. If you feel like added that capability please submit a pull request.

**Comment by jon49** [comment]
Sorry didn't tell you what is supported! The supported keywords can be seen here:

https://github.com/jon49/json-schema-to-mongoose/blob/master/lib/json-schema.js
